<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Departments</name>
   <tag></tag>
   <elementGuidId>6b130180-af36-44be-85f2-435835369e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[6]/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-link-row.child-menuLink-hover.parent-menu-row > a.child-menuLink-color.menulink-name.go-to-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Departments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf350b9d-659c-4136-b56d-941b9ca99c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>5fd37bf8-30eb-43ed-9044-f7d97403394e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>child-menuLink-color  menulink-name go-to-link</value>
      <webElementGuid>4fc6071f-8daf-47f9-b8fe-296502c99653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departments</value>
      <webElementGuid>19c7e641-b651-45ee-96a8-3b212c02086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;default&quot;]/div[@class=&quot;normal-menu  child-menuLink-background  leftAlign&quot;]/div[@class=&quot;normal-menulinks-wrapper&quot;]/div[@class=&quot;menu-link-row  child-menuLink-hover parent-menu-row&quot;]/a[@class=&quot;child-menuLink-color  menulink-name go-to-link&quot;]</value>
      <webElementGuid>e8cd0ed2-b404-49bc-a80a-1b3a90ca6bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[6]/div[2]/div[2]/a</value>
      <webElementGuid>a2872c59-3bef-43d1-9653-15157031a717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Departments')]</value>
      <webElementGuid>c3006610-171c-483c-b588-81050974e918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses'])[1]/following::a[1]</value>
      <webElementGuid>87f005b7-1516-4985-8472-cf51305b3c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::a[2]</value>
      <webElementGuid>e3472123-4368-40a6-92d4-adc9daca24d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG &amp; Research Dept. of History'])[1]/preceding::a[1]</value>
      <webElementGuid>745ed28f-4178-44d6-91b0-c8a9837e02fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG Dept. of Tamil'])[1]/preceding::a[2]</value>
      <webElementGuid>3dbb836b-5768-44e5-ae1a-0134a3634554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departments']/parent::*</value>
      <webElementGuid>bf606a99-a8f3-4ea1-802a-b08fbbeda2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>1a422068-5600-4179-bcf3-1519f58e6657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>0c9f1989-596f-4567-9371-22b900a79d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Departments' or . = 'Departments')]</value>
      <webElementGuid>53e2cccc-4b26-49df-ab9a-0cb8238fe74d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
