<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Download_HR3n_gallery-preview-footer undefined</name>
   <tag></tag>
   <elementGuidId>ee90a476-9278-4e5e-874e-a3266c72861d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-slider-holder']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.HR3n_gallery-preview-footer.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.HR3n_gallery-preview-footer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f9b3b54-023b-4495-8a70-3f264de110e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>HR3n_gallery-preview-footer undefined </value>
      <webElementGuid>acf436e6-4fe2-422c-86e5-266fe041d5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-slider-holder&quot;)/div[@class=&quot;njOA_preview-gallery-container undefined&quot;]/div[@class=&quot;BfXA_preview-header&quot;]/div[@class=&quot;HR3n_gallery-preview-footer undefined&quot;]</value>
      <webElementGuid>450e5238-124a-44ba-8040-fe9618f0ec8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-slider-holder']/div/div[2]/div</value>
      <webElementGuid>9d632925-e9c5-4fea-aa1b-4a6507d88485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::div[5]</value>
      <webElementGuid>6cc1abee-3adc-4910-85ad-79f97d5451a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/preceding::div[10]</value>
      <webElementGuid>5c4ec18c-2242-45d3-9353-661d218a11b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>527b2370-2256-4f92-96d4-be63985e08e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
