<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANTEEN</name>
   <tag></tag>
   <elementGuidId>0f9d3b3b-0766-412f-9787-f9bf4ee69cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[6]/div[2]/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CANTEEN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2cd7ee5b-15b7-466b-954e-9dd9dfb6f81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.melurgac.in/canteen/page-3238515</value>
      <webElementGuid>dccc6d90-57f9-4b01-a625-a4800d68ceba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>child-menuLink-color  menulink-name go-to-link</value>
      <webElementGuid>c6e9a18e-9809-4c13-a302-f7470f483d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANTEEN</value>
      <webElementGuid>cdebd22f-f38e-425d-b67f-2f80a0b82ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;default&quot;]/div[@class=&quot;normal-menu  child-menuLink-background  leftAlign&quot;]/div[@class=&quot;normal-menulinks-wrapper&quot;]/div[@class=&quot;menu-link-row  child-menuLink-hover&quot;]/a[@class=&quot;child-menuLink-color  menulink-name go-to-link&quot;]</value>
      <webElementGuid>61cc1d6d-06c3-4e31-8a8a-47cb95937861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[6]/div[2]/div[7]/a</value>
      <webElementGuid>dfa7bd58-d616-426e-ba4d-9d6e635fb052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANTEEN')]</value>
      <webElementGuid>5176739f-7dcd-4d40-84cf-12ee5f1c4c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CO-STORE'])[1]/following::a[1]</value>
      <webElementGuid>5998cafb-3ed9-4b9f-9938-ef016c7990f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GYM'])[1]/following::a[2]</value>
      <webElementGuid>36aeed9c-69cf-4655-a575-2c4f4d0e77e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOSTEL'])[1]/preceding::a[1]</value>
      <webElementGuid>a725d040-373d-498b-914d-85db5ac0bdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANTEEN']/parent::*</value>
      <webElementGuid>539dcd09-f5e8-418a-8662-bd27179f496e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.melurgac.in/canteen/page-3238515']</value>
      <webElementGuid>f371f671-b1e4-459c-8bb7-37dbc26c16a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>9c85f2d2-6ce8-44e4-9a4a-8d46251f44fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.melurgac.in/canteen/page-3238515' and (text() = 'CANTEEN' or . = 'CANTEEN')]</value>
      <webElementGuid>1d49ffc9-f704-404a-a2d0-e965caf88765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
