<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CLP</name>
   <tag></tag>
   <elementGuidId>9d90c3fa-cc5d-4869-85d1-7772db3858dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[6]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.child-menuLink-color.menulink-name.go-to-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CLP&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50da3bd5-daa8-486f-8762-9f538cc8c1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.melurgac.in/clp/page-3246941</value>
      <webElementGuid>aec12eed-bed9-4d94-9b4e-983fbd0a476d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>child-menuLink-color  menulink-name go-to-link</value>
      <webElementGuid>9ed31682-eeec-40ee-8268-1490751391d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLP</value>
      <webElementGuid>60e24382-df11-4823-8ee8-1495fc5b7648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;default&quot;]/div[@class=&quot;normal-menu  child-menuLink-background  leftAlign&quot;]/div[@class=&quot;normal-menulinks-wrapper&quot;]/div[@class=&quot;menu-link-row  child-menuLink-hover&quot;]/a[@class=&quot;child-menuLink-color  menulink-name go-to-link&quot;]</value>
      <webElementGuid>74c15647-5ae5-4fe0-8dbb-b064c8914282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[6]/div[2]/div/a</value>
      <webElementGuid>e4b3785d-c6c3-4368-9923-19027c45c617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CLP')]</value>
      <webElementGuid>8e91a755-9719-40e1-a6c0-97b475f7b750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::a[1]</value>
      <webElementGuid>618f117e-926f-4a08-84b7-2bef9d2ef9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Activities &amp; Facilities'])[1]/following::a[2]</value>
      <webElementGuid>a55c8078-d2cd-4688-a2da-b6dbe550bedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSS'])[1]/preceding::a[1]</value>
      <webElementGuid>676fb5b2-f079-46ca-a209-3d9decb4638b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RRC'])[1]/preceding::a[2]</value>
      <webElementGuid>11b68286-b3c8-4086-af53-a714c4e0834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLP']/parent::*</value>
      <webElementGuid>9e9a6571-1aa4-4a26-a4a3-3e669cbca2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.melurgac.in/clp/page-3246941']</value>
      <webElementGuid>564186a7-4579-4500-a25a-87d50a0c7876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>36bf15fa-e288-4a21-b987-bb6b67abc29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.melurgac.in/clp/page-3246941' and (text() = 'CLP' or . = 'CLP')]</value>
      <webElementGuid>a2590305-056e-4b5c-8ea2-ecd62a656414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
