<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>8c016b18-2a13-4598-8de8-ac7997a129ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menuzord-right']/ul/li[5]/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.megamenu.none > div.megamenu-row > div.col3 > ul.list-unstyled.list-dashed > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menuzord-right >> internal:role=link[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2a16f48-2059-400e-8f66-ae2f18b88bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>msuniv_education_home.php</value>
      <webElementGuid>3ab85490-ffab-4776-b8b7-184d5f6cf7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home</value>
      <webElementGuid>f69f9132-d556-46dd-be53-e9c5424b04b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuzord-right&quot;)/ul[@class=&quot;menuzord-menu menuzord-right menuzord-indented scrollable&quot;]/li[5]/div[@class=&quot;megamenu none&quot;]/div[@class=&quot;megamenu-row&quot;]/div[@class=&quot;col3&quot;]/ul[@class=&quot;list-unstyled list-dashed&quot;]/li[1]/a[1]</value>
      <webElementGuid>810aa621-7a9f-4382-8bbb-91c3b5f14b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menuzord-right']/ul/li[5]/div/div/div/ul/li/a</value>
      <webElementGuid>03b62a56-a2d5-4f61-b449-58305d3c4826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Home')])[2]</value>
      <webElementGuid>51636b8c-4c38-46ad-b3b3-fd951ea3a85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Examinations'])[1]/following::a[1]</value>
      <webElementGuid>2a12eb2a-fbb2-41bf-ad8f-ad0d84c034db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College Development Council'])[1]/following::a[2]</value>
      <webElementGuid>4eac44dd-0227-4118-a288-7e7aa440e870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result'])[1]/preceding::a[1]</value>
      <webElementGuid>d73279fc-53ca-4aeb-b085-7c6f81437260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Examiners Seniority'])[1]/preceding::a[2]</value>
      <webElementGuid>5efa8f13-cb76-495b-8c4e-6be95669eb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'msuniv_education_home.php')]</value>
      <webElementGuid>767e3895-9286-4e57-9e25-cffe27f89746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/ul/li/a</value>
      <webElementGuid>7d6bf139-02ac-4c7a-b3b7-f8c56d17c084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'msuniv_education_home.php' and (text() = ' Home' or . = ' Home')]</value>
      <webElementGuid>82f35e0c-9150-4f3f-9852-a69099dbeeea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
