<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANTEEN</name>
   <tag></tag>
   <elementGuidId>c5c587ae-f06d-4766-90c6-c098a5a5af92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[6]/div[2]/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CANTEEN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b74d4645-dcf5-45d6-9c9b-e4131eafc6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.melurgac.in/canteen/page-3238515</value>
      <webElementGuid>ce988af7-672a-460a-bf08-d7646d72e293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>child-menuLink-color  menulink-name go-to-link</value>
      <webElementGuid>959d67e7-d3d5-4a42-abd8-b3938ed9319b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANTEEN</value>
      <webElementGuid>80c1cbe1-98d2-44eb-94c9-fe5a9302d32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;default&quot;]/div[@class=&quot;normal-menu  child-menuLink-background  leftAlign&quot;]/div[@class=&quot;normal-menulinks-wrapper&quot;]/div[@class=&quot;menu-link-row  child-menuLink-hover&quot;]/a[@class=&quot;child-menuLink-color  menulink-name go-to-link&quot;]</value>
      <webElementGuid>8d70d14b-fe62-4066-bfed-b10b22a508b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[6]/div[2]/div[7]/a</value>
      <webElementGuid>515cfbd9-f7b4-4d0b-93af-f65448c2009b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANTEEN')]</value>
      <webElementGuid>8d997d29-362d-4e49-86ef-82e4b9f9decd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CO-STORE'])[1]/following::a[1]</value>
      <webElementGuid>8ac7cb86-4a3d-4182-a7ed-db15ec42f47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GYM'])[1]/following::a[2]</value>
      <webElementGuid>70c8d7fc-18e9-464b-8768-dea5f201784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOSTEL'])[1]/preceding::a[1]</value>
      <webElementGuid>8571bf20-32ac-40f6-8cce-13393780904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG Dept. of Tamil'])[1]/preceding::a[2]</value>
      <webElementGuid>34a608b7-83f5-4bba-8766-395f5e22bafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANTEEN']/parent::*</value>
      <webElementGuid>58204683-6c29-47a7-98ec-bf227209078e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.melurgac.in/canteen/page-3238515']</value>
      <webElementGuid>fe650b22-1724-49a9-a4dd-15923a364bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>32609263-f81c-4eaf-a28a-8db01faa25ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.melurgac.in/canteen/page-3238515' and (text() = 'CANTEEN' or . = 'CANTEEN')]</value>
      <webElementGuid>84e2ab5e-1fc6-439c-a284-097611b0f958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
